type StashBox {
  endpoint: String!
  api_key: String!
  name: String!
  max_requests_per_minute: Int!
}

input StashBoxInput {
  endpoint: String!
  api_key: String!
  name: String!
  # defaults to 240
  max_requests_per_minute: Int
}

type StashID {
  endpoint: String!
  stash_id: String!
  updated_at: Time!
}

input StashIDInput {
  endpoint: String!
  stash_id: String!
  updated_at: Time
}

input StashBoxFingerprintSubmissionInput {
  scene_ids: [String!]!
  stash_box_index: Int @deprecated(reason: "use stash_box_endpoint")
  stash_box_endpoint: String
}

input StashBoxDraftSubmissionInput {
  id: String!
  stash_box_index: Int @deprecated(reason: "use stash_box_endpoint")
  stash_box_endpoint: String
}

input StashBoxStudioScenesInput {
  "Index of the configured stash-box instance to use"
  stash_box_index: Int @deprecated(reason: "use stash_box_endpoint")
  "Endpoint of the stash-box instance to use"
  stash_box_endpoint: String
  "Stash-box studio ID"
  studio_id: ID!
}

type StashBoxStudioScene {
  id: ID!
  title: String
  date: String
  urls: [String!]!
  performers: [String!]!
  image_url: String
}

type StashBoxStudioScenesResult {
  count: Int!
  scenes: [StashBoxStudioScene!]!
}

input StashBoxPerformerScenesInput {
  "Index of the configured stash-box instance to use"
  stash_box_index: Int @deprecated(reason: "use stash_box_endpoint")
  "Endpoint of the stash-box instance to use"
  stash_box_endpoint: String
  "Stash-box performer ID"
  performer_id: ID!
}

type StashBoxPerformerScene {
  id: ID!
  title: String
  date: String
  urls: [String!]!
  performers: [String!]!
  studio: String
  parent_studio: String
  image_url: String
}

type StashBoxPerformerScenesResult {
  count: Int!
  scenes: [StashBoxPerformerScene!]!
}
